spring:
  main:
    web-application-type: reactive
  application:
    name: spring-cloud-api-gateway
              
      
server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://registration:8761/eureka}
  instance:
    preferIpAddress: true      