spring:
  application:
    name: spring-cloud-eureka-client-two

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://registration:8761/eureka}
  instance:
    preferIpAddress: true